package com.pricingia.saas.modules.pricing.integration;

import com.pricingia.saas.modules.shopify.domain.ShopifyHmacVerifier;
import com.pricingia.saas.modules.webhook.domain.ShopifyWebhookHeaders;
import com.pricingia.saas.support.integration.WebIntegrationTest;
import org.junit.jupiter.api.Test;

import java.net.http.HttpResponse;
import java.util.HashMap;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * End-to-end: valid webhook -> RabbitMQ -> consumer -> pricing engine -> price decision.
 */
class WebhookToPriceDecisionFlowIT extends WebIntegrationTest {

	@Test
	void validWebhookShouldEventuallyProduceAPriceDecision() throws Exception {
		// Ensure automation is on with a minimum margin above the demo product margin.
		putJson("/api/merchant/settings", """
				{
				  "currency": "USD",
				  "minMarginPercentage": 30.00,
				  "maxPriceIncreasePercentage": 15.00,
				  "automationEnabled": true
				}
				""");

		// Seed a monitored product (margin 20% < 30% min -> should be SUGGESTED).
		assertThat(postJson("/api/products/demo", null).statusCode()).isEqualTo(201);

		String body = "{\"shopify_product_id\":\"gid://shopify/Product/1001\",\"topic\":\"products/update\"}";
		String hmac = ShopifyHmacVerifier.computeBase64(WEBHOOK_SECRET, body);

		Map<String, String> headers = new HashMap<>();
		headers.put(ShopifyWebhookHeaders.HEADER_HMAC, hmac);
		headers.put(ShopifyWebhookHeaders.HEADER_WEBHOOK_ID, "it-flow-" + System.nanoTime());
		headers.put(ShopifyWebhookHeaders.HEADER_TOPIC, "products/update");
		headers.put(ShopifyWebhookHeaders.HEADER_SHOP_DOMAIN, "demo-shop.myshopify.com");

		HttpResponse<String> webhook = postWithHeaders("/webhooks/shopify", body, headers);
		assertThat(webhook.statusCode()).isEqualTo(200);

		boolean suggestedFound = waitForSuggestedDecision();
		assertThat(suggestedFound)
				.as("a SUGGESTED price decision should be generated by the consumer")
				.isTrue();
	}

	private boolean waitForSuggestedDecision() throws Exception {
		long deadline = System.currentTimeMillis() + 15_000;
		while (System.currentTimeMillis() < deadline) {
			HttpResponse<String> decisions = get("/api/pricing/decisions");
			if (decisions.statusCode() == 200 && decisions.body().contains("\"status\":\"SUGGESTED\"")) {
				return true;
			}
			Thread.sleep(300);
		}
		return false;
	}
}
